from __future__ import annotations

from enum import Enum


class PaymentStatus(str, Enum):
    NEW = "NEW"
    FORM_SHOWED = "FORM_SHOWED"
    AUTHORIZING = "AUTHORIZING"
    AUTHORIZED = "AUTHORIZED"
    CONFIRMING = "CONFIRMING"
    CONFIRMED = "CONFIRMED"
    REVERSING = "REVERSING"
    REVERSED = "REVERSED"
    REFUNDING = "REFUNDING"
    REFUNDED = "REFUNDED"
    PARTIAL_REFUNDED = "PARTIAL_REFUNDED"
    REJECTED = "REJECTED"
    DEADLINE_EXPIRED = "DEADLINE_EXPIRED"
    CANCELED = "CANCELED"
